In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Social_Network_Ads.csv')
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [3]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.05, random_state = 42)

In [8]:
x_train

array([[    22,  27000],
       [    29,  80000],
       [    47,  23000],
       [    59,  76000],
       [    19,  19000],
       [    51,  23000],
       [    42,  80000],
       [    37,  53000],
       [    55, 125000],
       [    19,  21000],
       [    46,  41000],
       [    19,  70000],
       [    36, 144000],
       [    28,  79000],
       [    40, 107000],
       [    35,  75000],
       [    37,  55000],
       [    38,  65000],
       [    26,  30000],
       [    18,  68000],
       [    48,  33000],
       [    24,  55000],
       [    18,  52000],
       [    47,  20000],
       [    20,  49000],
       [    44, 139000],
       [    29,  61000],
       [    31,  71000],
       [    48,  41000],
       [    34,  43000],
       [    25,  79000],
       [    53,  82000],
       [    38,  55000],
       [    25,  80000],
       [    37,  80000],
       [    27,  31000],
       [    60, 102000],
       [    26, 118000],
       [    31,  74000],
       [    31,  76000],


In [9]:
x_test

array([[    46,  22000],
       [    59,  88000],
       [    28,  44000],
       [    48,  96000],
       [    29,  28000],
       [    30,  62000],
       [    47, 107000],
       [    29,  83000],
       [    40,  75000],
       [    42,  65000],
       [    35,  65000],
       [    53,  34000],
       [    23,  48000],
       [    20,  23000],
       [    30,  87000],
       [    35, 108000],
       [    52,  38000],
       [    46,  74000],
       [    39,  42000],
       [    56,  60000]], dtype=int64)

In [10]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,

In [11]:
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
      dtype=int64)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [14]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [15]:
x_train

array([[-1.4922053 , -1.25485135],
       [-0.8211544 ,  0.28729572],
       [ 0.90440507, -1.3712398 ],
       [ 2.05477806,  0.17090726],
       [-1.77979855, -1.48762826],
       [ 1.28786274, -1.3712398 ],
       [ 0.425083  ,  0.28729572],
       [-0.05423908, -0.49832637],
       [ 1.6713204 ,  1.59666587],
       [-1.77979855, -1.42943403],
       [ 0.80854066, -0.84749174],
       [-1.77979855, -0.00367542],
       [-0.15010349,  2.14951104],
       [-0.91701881,  0.25819861],
       [ 0.23335417,  1.07291781],
       [-0.24596791,  0.14181015],
       [-0.05423908, -0.44013214],
       [ 0.04162534, -0.149161  ],
       [-1.10874764, -1.16756   ],
       [-1.87566297, -0.06186965],
       [ 1.00026949, -1.08026866],
       [-1.30047647, -0.44013214],
       [-1.87566297, -0.52742349],
       [ 0.90440507, -1.45853115],
       [-1.68393414, -0.61471483],
       [ 0.61681183,  2.00402547],
       [-0.8211544 , -0.26554946],
       [-0.62942557,  0.02542169],
       [ 1.00026949,

In [16]:
x_test

array([[ 0.6024888 , -1.53287067],
       [ 1.78028646,  0.96822857],
       [-1.02830795, -0.69917093],
       [ 0.78368844,  1.27139212],
       [-0.93770813, -1.30549802],
       [-0.84710832, -0.01705295],
       [ 0.69308862,  1.68824199],
       [-0.93770813,  0.77875136],
       [ 0.05888988,  0.47558781],
       [ 0.24008952,  0.09663338],
       [-0.39410922,  0.09663338],
       [ 1.23668754, -1.07812536],
       [-1.48130705, -0.54758915],
       [-1.75310651, -1.49497523],
       [-0.84710832,  0.93033313],
       [-0.39410922,  1.72613743],
       [ 1.14608772, -0.92654358],
       [ 0.6024888 ,  0.43769237],
       [-0.03170994, -0.77496181],
       [ 1.508487  , -0.09284384]])

# Creating Model --> SVM (Support Vector Machine)

In [17]:
from sklearn.svm import SVC

In [19]:
classifier = SVC(kernel = 'linear', random_state = 0)

In [20]:
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

# Predictions

In [21]:
print(classifier.predict(sc.transform([[32, 150000]]))[0])

1


In [22]:
print(classifier.predict(sc.transform([[20, 86000]]))[0])

0


In [23]:
y_prediction = classifier.predict(x_test)

In [24]:
y_prediction

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1],
      dtype=int64)

In [25]:
print(np.concatenate((y_prediction.reshape(len(y_prediction), 1), y_test.reshape(len(y_test), 1)), 1)) # [Prediction, Actual]

[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 0]
 [0 0]
 [1 1]]


## Confusion Matrix and Accuracy

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
cm = confusion_matrix(y_test, y_prediction) # See in Google... [correct, wrong] ... We can use confusion matrix to evaluate our model.
cm                                                           # [wrong, correct]

array([[12,  2],
       [ 0,  6]], dtype=int64)

In [28]:
accuracy_score(y_test, y_prediction) # Accuracy of 90% is achieved.

0.9

In [29]:
# Logistic Regression
# Support Vector Machine
# K - Nearest Negihbour (KNN)
# Kernal SVM
# Naive Bayes
# Decision Tree Classification
# Random Forest Classification